# clusterissuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cristian_luna@alumni.brown.edu
    privateKeySecretRef:
      name: letsencrypt-account-private-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx